// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  gettingStartedSidebar: [
    {
      type: 'autogenerated',
      dirName: 'getting-started',
    },
  ],
  foundationsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'foundations',
    },
  ],
  componentsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'components',
    },
  ],
};

export default sidebars;
